<table class="table table-striped">
    <tbody>
    <tr>
        <th style="width: 10px"><?php echo _a('ID'); ?></th>
        <th style="width: 10px"><?php echo _a('Thumbnail'); ?></th>
        <th style="width: 10px"><?php echo _a('Status'); ?></th>
        <th style="width: 20%;"><?php echo _a('Title'); ?></th>
        <th style="width: 40px;"><?php echo _a('Mimetype'); ?></th>
        <th style="width: 80px;"><?php echo _a('Date') ?></th>
    </tr>
    <?php
    foreach ($medias as $media) {
        $media['active'] = (int) $media['active'];
        ?>
        <tr>
            <td>
                <?php echo $media['id']; ?>
            </td>
            <td>
                <?php if($img = Pi::api('resize','media')->resize($media)->thumbcrop(100, 100)) : ?>
                    <img src="<?php echo $img ?>" />
                <?php endif; ?>
            </td>
            <td>
                <?php switch ($media['active']): case 0: ?>
                    <span class="label label-default">Disabled</span>
                    <?php break; case 1: ?>
                    <span class="label label-success">Enabled</span>
                    <?php break; case 2: ?>
                    <span class="label label-warning">Soft deleted</span>
                    <?php break; endswitch; ?>
            </td>
            <td>
                <?php echo $media['title']; ?>
                <div class="row-actions one-action">
                    <a href="<?php echo $this->url($section, array(
                        'controller'    => 'modal',
                        'action'        => 'edit',
                        'id'            => $media['id'],
                    )); ?>" data-value="edit"><?php echo _a('Edit'); ?></a> |

                    <?php if($media['time_deleted']) : ?>
                        <a href="<?php echo $this->url($section, array(
                            'controller'    => 'modal',
                            'action'        => 'undelete',
                            'id'            => $media['id'],
                        )); ?>" data-value="Undelete">
                            <?php echo _a('Undelete'); ?>
                        </a> |
                    <?php else: ?>
                        <a href="<?php echo $this->url($section, array(
                            'controller'    => 'modal',
                            'action'        => 'delete',
                            'id'            => $media['id'],
                        )); ?>" data-value="delete">
                            <?php echo _a('Delete'); ?>
                        </a> |
                    <?php endif; ?>
                    <a class="no-ajax" href="<?php echo Pi::api('doc', 'media')->getUrl($media['id']) ?>" target="_blank">
                        <?php echo _a('Download'); ?>
                    </a>
                </div>
            </td>
            <td><?php echo $this->escape($media['mimetype']); ?></td>
            <td><?php echo _date($media['time_created']); ?></td>
        </tr>
    <?php } ?>

    <?php if (!count($medias)) : ?>
        <tr>
            <td colspan="100000">
                <?php echo _a('No resource available yet.'); ?>
            </td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>

<?php
if (count($medias) && $paginator) {
    echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml');
}
?>