<?php
    $this->css($this->assetModule('script/admin.css'));
?>

<?php echo $this->tab($tabs); ?>

<div id="pi-js-media">
    <div class="pi-media-list">
        <table class="table table-striped">
            <tbody>
                <tr>
                    <th style="width: 10px"><?php echo _a('ID'); ?></th>
                    <th><?php echo _a('Title'); ?></th>
                    <th><?php echo _a('Main image'); ?></th>
                    <th><?php echo _a('Additional images'); ?></th>
                    <th style="width: 10px"><?php echo _a('Actions'); ?></th>
                </tr>
                <?php foreach ($tests as $test) : ?>
                    <tr>
                        <td>
                            <?php echo $test['id']; ?>
                        </td>
                        <td>
                            <?php echo $test['title']; ?>
                        </td>
                        <td>
                            <?php if($img = Pi::api('doc','media')->getResizedSingleLinkUrl($test['main_image'])->thumbcrop(100, 100)) : ?>
                                <img class="img-thumbnail" src="<?php echo $img ?>" />
                            <?php else : ?>
                                Doc ?
                            <?php endif; ?>

                            <br />
                            <a href="<?php echo Pi::api('doc','media')->getOriginalSingleLinkUrl($test['main_image']) ?>" target="_blank">Download media</a>
                        </td>
                        <td>
                            <?php $galleryImages = Pi::api('doc','media')->getOriginalGalleryLinkData($test['additional_images']) ?>
                            <?php foreach($galleryImages as $key => $galleryImage) : ?>
                                <a href="<?php echo $galleryImage['url'] ?>" target="_blank">Download media #<?php echo $key ?></a><br />
                            <?php endforeach; ?>
                        </td>
                        <td>
                            <a href="<?php echo $this->url('', array('action' => 'edit', 'id' => $test['id'])); ?>" class="btn btn-primary btn-xs"><?php echo _a('Update'); ?></a>
                            <br><br>
                            <a href="<?php echo $this->url('', array('action' => 'remove', 'id' => $test['id'])); ?>" class="btn btn-danger  btn-xs"><?php echo _a('Delete'); ?></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    
    <?php
        if (!empty($medias) && $paginator) {
            echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml');
        }
    ?>
</div>