<?php
    $this->css($this->assetModule('script/admin.css'));
?>

<?php echo $this->tab($tabs); ?>

<div id="pi-js-media">
    <div class="pi-media-list">
        <table class="table table-striped">
            <tbody>
                <tr>
                    <th style="width: 10px"><?php echo _a('ID'); ?></th>
                    <th><?php echo _a('Title'); ?></th>
                    <th><?php echo _a('Main image'); ?></th>
                    <th style="width: 10px"><?php echo _a('Actions'); ?></th>
                </tr>
                <?php foreach ($tests as $test) : ?>
                    <tr>
                        <td>
                            <?php echo $test['id']; ?>
                        </td>
                        <td>
                            <?php echo $test['title']; ?>
                        </td>
                        <td>
                            --
                        </td>
                        <td>
                            <a href="<?php echo $this->url('', array('action' => 'edit', 'id' => $test['id'])); ?>" class="btn btn-primary btn-xs"><?php echo _a('Update'); ?></a>
                            <br><br>
                            <a href="<?php echo $this->url('', array('action' => 'remove', 'id' => $test['id'])); ?>" class="btn btn-danger  btn-xs"><?php echo _a('Delete'); ?></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    
    <?php
        if (!empty($medias) && $paginator) {
            echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml');
        }
    ?>
</div>