<?php
    $this->css($this->assetModule('script/admin.css'));
    $this->jquery();
    $this->js(Pi::url('public/vendor/bootstrap/js/bootstrap.js'));
?>
<div class="clearfix">
    <?php if (isset($message)) { ?>
        <div class="alert alert-danger">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php echo $message; ?>
        </div>
    <?php } ?>
    <div class="alert alert-success" role="alert">
        <?php _e('You can use this page tools for better manage your media'); ?>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <?php echo _a('Fill empty descriptions from media title'); ?>
                </div>
                <div class="card-body">
                    <p>
                        <?php echo _a('This tool help you to put description from media title to empty description media'); ?>
                    </p>
                    <p>
                        <a href="<?php echo $this->url('', array('action' => 'fillDescription')); ?>" class="btn btn-primary btn-sm">
                            <i class="fas fa-cog" aria-hidden="true"></i>
                            <?php echo _a('Fill empty descriptions from media title'); ?>
                        </a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <?php echo _a('Clean cache for orpheaned media'); ?>
                </div>
                <div class="card-body">
                    <p>
                        <?php echo _a('This tool can clean your server by removing cache medias that are not used on any linked content'); ?>
                    </p>
                    <p>
                        <a href="<?php echo $this->url('', array('action' => 'removeOrphaned')); ?>" class="btn btn-primary btn-sm">
                            <i class="fas fa-cog" aria-hidden="true"></i>
                            <?php echo _a('Clean cache for orpheaned media'); ?>
                        </a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <?php echo _a('Hard delete soft-deleted media'); ?>
                </div>
                <div class="card-body">
                    <p>
                        <?php echo _a('This tool can clean your server by removing soft deleted media'); ?>
                    </p>
                    <p>
                        <a href="<?php echo $this->url('', array('action' => 'cleanSoftDeletedMedia')); ?>" class="btn btn-primary btn-sm">
                            <i class="fas fa-cog" aria-hidden="true"></i>
                            <?php echo _a('Hard delete soft-deleted media'); ?>
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>