<ul class="media-list media-list-sortable <?php echo $haveToComplete ? 'media-list-incomplete' : '' ?>">
    <?php if(count($medias)) : ?>
        <?php foreach($medias as $media) : ?>
            <?php $hasInvalidFields = Pi::api('doc', 'media')->hasInvalidFields($media) ?>
            <li class=" ui-state-default <?php echo $hasInvalidFields ? 'invalid-media' : '' ?>" data-media-id="<?php echo $media['id'] ?>">
                <div class="box">
                    <?php if($img = Pi::api('resize','media')->resizeFormList($media)) : ?>
                        <img class="img-thumbnail" src="<?php echo $img ?>" />
                    <?php else : ?>
                            <?php echo $media['title'] ?>
                    <?php endif; ?>
                </div>

                <hr />
                <button type="button" class="btn btn-warning btn-xs btn-complete-action" href="#" data-media-id="<?php echo $media['id'] ?>" data-toggle="modal" data-target="#editMediaModal"><?php echo __('Complete') ?></button>
                <button type="button" class="btn btn-default btn-xs btn-edit-action" href="#" data-media-id="<?php echo $media['id'] ?>" data-toggle="modal" data-target="#editMediaModal"><?php echo __('Edit') ?></button>
            </li>
        <?php endforeach; ?>
    <?php else : ?>
        <li class="ui-state-default"><?php echo __('No media for now...') ?></li>
    <?php endif; ?>
</ul>

<div class="media-alert clearfix text-center hide">
    <span class="label label-danger"><?php echo __('You have to complete file informations before submit') ?></span>
</div>