<?php $hash = rand(); ?>
<?php if(count($medias)) : ?>
    <ul class="hash-<?php echo $hash ?> media-list media-list-sortable <?php echo $haveToComplete ? 'media-list-incomplete' : '' ?>">
        <?php foreach($medias as $media) : ?>
            <?php $hasInvalidFields = Pi::api('doc', 'media')->hasInvalidFields($media) ?>
            <li class=" ui-state-default <?php echo $hasInvalidFields ? 'invalid-media' : '' ?>" data-media-id="<?php echo $media['id'] ?>" data-media-season="<?php echo $media['season'] ?>">
                <div class="box">
                    <?php if($img = Pi::api('resize','media')->resizeFormList($media)) : ?>
                        <img class="img-thumbnail" src="<?php echo $img ?>" />
                    <?php else : ?>
                        <?php echo $media['title'] ?>
                    <?php endif; ?>
                </div>
                <hr />
                <?php if(\Pi::engine()->section() == 'admin' || $media['uid'] == \Pi::user()->getId()) : ?>
                    <?php if($hasInvalidFields) : ?>
                        <button type="button" class="btn btn-danger btn-sm btn-complete-action btn-sm" href="#" data-media-id="<?php echo $media['id'] ?>" data-toggle="modal" data-target="#editMediaModal"><?php echo __('Complete') ?></button>
                    <?php else : ?>
                        <button type="button" class="btn btn-secondary btn-sm btn-edit-action btn-sm" href="#" data-media-id="<?php echo $media['id'] ?>" data-toggle="modal" data-target="#editMediaModal"><?php echo __('Edit') ?></button>
                    <?php endif ?>
                <?php endif; ?>
                <button type="button" class="btn btn-warning btn-sm btn-unlink-action" href="#" data-media-id="<?php echo $media['id'] ?>">
                    <span class="glyphicon glyphicon-remove"></span>
                    <?php echo __('Unlink') ?>
                </button>
            </li>
        <?php endforeach; ?>
    </ul>

    <script>
        jQuery('.hash-<?php echo $hash ?>').parent('.media-form-list').parent('.card-body').show();
    </script>
<?php else : ?>
    <span class="hash-<?php echo $hash ?>"></span>
    <script>
        jQuery('.hash-<?php echo $hash ?>').parent('.media-form-list').parent('.card-body').hide();
    </script>
<?php endif; ?>

<div class="media-alert clearfix text-center d-none">
    <span class="badge badge-danger"><?php echo __('You have to complete file informations before submit') ?></span>
</div>