<table class="table table-striped">
    <thead>
    <tr>
        <th style="width: 10px"></th>
        <th style="width: 10px"><?php echo _a('Thumbnail'); ?></th>
        <th><?php echo _a('Title'); ?></th>
        <th><?php echo _a('Date'); ?></th>
        <th style="width: 40px;"></th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($medias as $media) {
        $media['active'] = (int) $media['active'];
        ?>
        <tr data-media-id="<?php echo $media['id']; ?>">
            <td class="checked-column">
                <span class="glyphicon glyphicon-ok"></span>
            </td>
            <td>
                <?php if($img = Pi::api('resize','media')->resize($media)->thumbcrop(100, 100)) : ?>
                    <img src="<?php echo $img ?>" />
                <?php endif; ?>
            </td>
            <td>
                <?php echo $media['title']; ?>
            </td>
            <td><?php echo _date($media['time_created']); ?></td>
            <td>
                <?php if(!$media['time_deleted']) : ?>
                    <a class="btn btn-danger btn-xs do-ajax" href="<?php echo $this->url($section, array(
                        'controller'    => 'modal',
                        'action'        => 'delete',
                        'id'            => $media['id'],
                    )); ?>" data-value="delete">
                        <span class="glyphicon glyphicon-remove"></span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php } ?>

    <?php if (!count($medias)) : ?>
        <tr>
            <td colspan="100000">
                <?php echo _a('No resource available yet.'); ?>
            </td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>