<?php $hash = rand(); ?>
<?php if(count($medias)) : ?>
    <ul class="hash-<?php echo $hash ?>">
        <?php foreach($medias as $media) : ?>
            <?php $hasInvalidFields = Pi::api('doc', 'media')->hasInvalidFields($media) ?>
            <li class=" ui-state-default <?php echo $hasInvalidFields ? 'invalid-media' : '' ?>" data-media-id="<?php echo $media['id'] ?>" data-media-season="<?php echo $media['season'] ?>">
                <div class="box">
                    <?php if($img = Pi::api('resize','media')->resizeFormList($media)) : ?>
                        <img class="img-thumbnail" src="<?php echo $img ?>" />
                    <?php else : ?>
                        <?php echo $media['title'] ?>
                    <?php endif; ?>
                </div>
                <hr />
                <?php if(\Pi::engine()->section() == 'admin' || $media['uid'] == \Pi::user()->getId()) : ?>
                    <button type="button" class="btn btn-danger btn-xs btn-complete-action" href="#" data-media-id="<?php echo $media['id'] ?>" data-toggle="modal" data-target="#editMediaModal"><?php echo __('Complete') ?></button>
                    <button type="button" class="btn btn-default btn-xs btn-edit-action" href="#" data-media-id="<?php echo $media['id'] ?>" data-toggle="modal" data-target="#editMediaModal"><?php echo __('Edit') ?></button>
                <?php endif; ?>
                <button type="button" class="btn btn-warning btn-xs btn-unlink-action" href="#" data-media-id="<?php echo $media['id'] ?>">
                    <span class="glyphicon glyphicon-remove"></span>
                    <?php echo __('Unlink') ?>
                </button>
            </li>
        <?php endforeach; ?>
    </ul>

    <script>
        jQuery('.hash-<?php echo $hash ?>').parent('.media-form-list').parent('.panel-body').show();
    </script>
<?php else : ?>
    <span class="hash-<?php echo $hash ?>"></span>
    <script>
        jQuery('.hash-<?php echo $hash ?>').parent('.media-form-list').parent('.panel-body').hide();
    </script>
<?php endif; ?>

<div class="media-alert clearfix text-center hide">
    <span class="label label-danger"><?php echo __('You have to complete file informations before submit') ?></span>
</div>